name: omni_media_picker
description: "A Flutter plugin to capture multiple media from the device."
version: 0.1.0
homepage: https://github.com/tushshah4442/omni_media_picker.git
repository: https://github.com/tushshah4442/omni_media_picker.git
issue_tracker: https://github.com/tushshah4442/omni_media_picker/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

